/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.pa2122.jlogo105504.app;

import java.io.File;
import java.util.Scanner;

/**
 * This class represent the LOGO Application.
 */
public class Logo {

    public static void main(String[] args) {
        File input = null;
        File output = null;

        new Logo().askForInputFile(new Scanner(System.in));
        //new Logo().askForOutputFile(new Scanner(System.in));
    }

    /**
     * This private method is used to ask the input file to user.
     *
     * @param scanner the scanner
     * @return the file take in input from the user
     */
    private File askForInputFile(Scanner scanner){
        File file = null;
        while (file == null) {
            System.out.println("Insert input file:");
            File inputFile = new File(scanner.nextLine());
            if (!inputFile.isFile() || !inputFile.exists()) {
                System.out.println("Error!! File not found, try again.");
                continue;
            }
            file = inputFile;
        }
        return file;
    }

    private File askForOutputFile(Scanner scanner) {
        return null;
    }
}
